### PR TITLE
add nginx proxy parameters

### PR DESCRIPTION
**Pull request by nextgen-networks**
add parameters to utilize nginx proxy (if you don't use Apache)

### CODE REVIEW

**Comment by Igortorrente** [comment]
Hi @nextgen-networks,  can you rebase the commit so I can merge it? Thanks!!

**Comment by nextgen-networks** [comment]
will create new PR and close this

**Comment by Igortorrente** [comment]
You don't need do that, just rebase and `git push --force` the branch

**Comment by nextgen-networks** [comment]
> You don't need do that, just rebase and `git push --force` the branch

... was easier/faster for me to do it that way ;-) - because have no local git branch on any of my machines - so no git cli.

**Comment by Igortorrente** [comment]
Ok, np :)
Thanks for your PR :)

**Comment by nextgen-networks** [comment]
> Ok, np :)
> Thanks for your PR :)

Thanks to YOU for your crazy big efforts in cleaning up the code and refactor this plugin to become one of the best possible webmail solutions for NC.

**Comment by nextgen-networks** [comment]
Hello Igortorrente,

I've for no contact information on your Github profile therefore trying 
to get in contact with you that way :-)

At first I want to sage huuuge thanks for your ongoing refinement 
efforts to the NC-Roundcube plugin!
I've tried to get this running with my very limited PHP knowledge a very 
long time (and was not successful).
Together with the baseline from flionet89 you did a very big favor to 
the community - and if possible I like to do a little favor to you.

Is there any possibility to donate a small amount of bucks to you (e.g. 
via PayPal)?

Cheers from Hamburg/Germany

Ralf

-- 
Nextgen-Networks
Ralf Goeldner
Sven-Hedin-Straße 11
22523 Hamburg
Germany

I-Net: http://www.nextgen-networks.de
Mobil: +49 (0)172 - 3243698
Tel.: +49 (0)40 - 25764109
Fax: +49 (0)40 - 25764110

USt-IdNr./VAT-ID: DE243301378

**Comment by Igortorrente** [comment]
> Hello Igortorrente,
> 
> I've for no contact information on your Github profile therefore trying
> to get in contact with you that way :-)
> 
> At first I want to sage huuuge thanks for your ongoing refinement
> efforts to the NC-Roundcube plugin!

Very nice to see that was useful to another person beyond than me :)

> I've tried to get this running with my very limited PHP knowledge a very
> long time (and was not successful).

I also had non-existent PHP knowledge before digging into the code. 

> Together with the baseline from flionet89 you did a very big favor to
> the community - and if possible I like to do a little favor to you.
> 
> Is there any possibility to donate a small amount of bucks to you (e.g.
> via PayPal)?

I wasn't expecting that. I had to ask my brother for his PayPal.

I think you can send it [here](https://www.paypal.com/donate?hosted_button_id=P6GQAL2QJYEFY) if you want to.

> 
> Cheers from Hamburg/Germany

Cheers from São Paulo/Brazil :)

> 
> Ralf
> …
> 
> -- 
> Nextgen-Networks
> Ralf Goeldner
> Sven-Hedin-Straße 11
> 22523 Hamburg
> Germany
> 
> I-Net: http://www.nextgen-networks.de
> Mobil: +49 (0)172 - 3243698
> Tel.: +49 (0)40 - 25764109
> Fax: +49 (0)40 - 25764110
> 
> USt-IdNr./VAT-ID: DE243301378
>

**Pull request closed without merging**
